name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@80f10bf419f34980065523f5efca7ebed17576aa # v4
        with:
          config-file: ./.github/dependency-review-config.yml
